export const
  GET_REQUEST = 'GET_REQUEST',
  GET_REQUEST_SUCCESS = 'GET_REQUEST_SUCCESS',
  GET_REQUEST_FAIL = 'GET_REQUEST_FAIL',
  UPDATE_REQUEST = 'UPDATE_REQUEST',
  UPDATE_REQUEST_SUCCESS = 'UPDATE_REQUEST_SUCCESS',
  UPDATE_REQUEST_FAIL = 'UPDATE_REQUEST_FAIL';
